# fly.toml app configuration file generated for n8nsoda on 2025-08-31T19:11:41Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'n8nsoda'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
