app = "n8nsoda"
primary_region = "otp"

[build]

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = "stop"  # Fly geçerli bir değer kabul ediyor
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 2
